### ISSUE TITLE
Lag en checkbox for påmelding til nyhetsbrev (som må registreres hos Mailchimp manuelt)

### ISSUE THREAD

**Issue by AndreasII** [stiftelsen-effekt/effekt-frontend#27]
For å gi donorer mulighet til å melde seg på nyhetsbrevet vårt ønsker vi å legge til en checkbox der man kan huke av for å melde seg på nyhetsbrevet vårt. 

Bekreftelsen lagres på donoren i databasen, og kan deretter hentes ut manuelt for å melde donorer opp til nyhetsbrevet.

**Comment by Mofoss** [comment]
Jeg lukker denne pga duplikat av annen issue (forsøker så å fikse den når tid):
https://github.com/stiftelsen-effekt/effekt-frontend/issues/25
