### ISSUE TITLE
Fjern krav om adresse i PayPal-APIet

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-frontend#35]
Hvis man velger å betale med kort i PayPal-løsningen i dag så må man, i motsetning til i en del andre betalingsløsninger med kort, også legge inn adresse (det er obligatorisk). Dette virker unødvendig. 

Det kan se ut til at det er mulig å skru av denne funksjonaliteten, fra det jeg ser på ulike forum, selv om jeg ikke finner det i dokumentasjonen. Er dog usikker på hvilket API vi bruker. Se f.eks.:

"If you're using the newer API, you could also pass NOSHIPPING=1"

En annen skriver (OBS: muligens er dette dog for en annet API-versjon):
"Allowable values:
0 – prompt for an address, but do not require one
1 – do not prompt for an address
2 – prompt for an address, and require one
The default is 0."

Generell dokumentasjon: https://developer.paypal.com/classic-home/

**Comment by AndreasII** [comment]
StackOverflow-tråd om problemet. https://stackoverflow.com/questions/28951320/paypal-api-take-immediate-payment-without-a-shipping-address

Muligens relevant, men godt mulig at det er utdatert informasjon.

**Comment by fellmirr** [comment]
Dette ser ikke ut til å være mulig. Det de snakker om i alle tråder jeg ser er shipping address. Vi må tilsynelatende alltid oppgi addresse til paypal for kortbetaling, antagelig av compliance grunner? (PayPal skal vite hvem kundene sine er).

Lukke issue?

**Comment by AndreasII** [comment]
ok!
