### ISSUE TITLE
Epost mangler kontonr

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-frontend#37]
Ved valg av donasjon med bank så mangler det nå kontonummer på eposten jeg får "Donasjon klar for innbetaling". Se bilde som kommentar.

Dessuten lurer jeg på, som en liten tilleggsendring: kan vi endre i teksten i eposten der det står "sette opp overføringen med melding, og skrive KIDen i meldingsfeltet, f.eks. "KID: 12345678" til å bruke den faktiske KID'en i stedet?

Altså noe sånt i html: ".....og skrive KIDen i meldingsfeltet. Skriv da “KID: < ?= donor.KID ? >" i meldingsfeltet." (uten mellomrom mellom < ? og ? >)

**Comment by Mofoss** [comment]
![image](https://user-images.githubusercontent.com/17338692/79562953-27484780-80ac-11ea-8c35-8e89a49c5aea.png)

Det er også et merkelig innrykk på kontonr og KID. Dessuten tror jeg kanskje vi bør fjerne mellomrommene mellom KID'en om folk kopierer den. Eller? (dette er ikke så viktig, dog)

**Comment by fellmirr** [comment]
Ajaj, det har du helt rett i, jeg har glemt å slenge med den variablen i cloud run. Should be but a moment, så er det i orden! Den feilen har vært der i ca. 6 timer.

**Comment by Mofoss** [comment]
Ja, jeg regnet med det. Ikke noe problem i det hele tatt, det er jo uansett lett å finne. Antok det var noe ifm oppgraderingen så tagget deg bare direkte =)

**Comment by fellmirr** [comment]
![image](https://user-images.githubusercontent.com/693641/79565854-cde31700-80b1-11ea-921c-383d2e7e66be.png)

**Comment by Mofoss** [comment]
Perfekt! Godt jobbet, Håkon! :-D
