### ISSUE TITLE
Legge til mulighet for å skjule referral kategorier

### ISSUE THREAD

**Issue by Mofoss** [stiftelsen-effekt/effekt-frontend#39]
Kunne vi fått til å legge til en is_active-variabel i Referral_types-tabellen i DB, likt på Organizations, og at bare de som markeres som aktiv vises fram i widgeten? 

Det ville vært fint å kunne inaktivere noen av de mindre vanlige kategoriene, eller for kampanjer som er ferdige. 

I dag kommer alle kategorier fra databasen direkte inn i widgeten, men hvis jeg forstår rett kan vi altså legge til en kolonne is_active samt endre på widgeten (og et API?) som henter disse.

**Comment by fellmirr** [comment]
Dette var veldig fort gjort så bare ordna det.

Ligger nå to nye kolonner, en is_active kolonne og er ordering kolonne (for å styre rekkefølgen de kommer ut i).

**Comment by Mofoss** [comment]
Perfekt! Tusen takk, @fellmirr!
